### ISSUE TITLE
Retrieve affymetrix and RNA-seq data through webservice

### ISSUE THREAD

**Issue by julien-roux** [wirawara/BgeeDB#5]
Right now, Affy and RNA-seq data are downloaded trhough the FTP website. It would be more flexible, more elegant, and more harmonious with the topAnat part to retrieve the data through a web-service.

This is not a high priority though...

**Comment by julien-roux** [comment]
Andrea's comment: wouldn’t that slow up the process of downloading? `GEOquery` is using ftp as well.

**Comment by fbastian** [comment]
Is it possible to determine when a FTP file transfer is not successfully completed? Otherwise, we would need at some point to add checksums of our files on the FTP, so that we check that downloaded files are not corrupted before storing them in cache? Or use the webservice instead?

**Comment by julien-roux** [comment]
Added https://github.com/BgeeDB/BgeeDB_R/issues/9

-> Closing this issue
